USE MUNICIPAL_ERP;
SELECT * INTO DBO.EMP_REMUNERATION FROM DBO.stg_emp_remuneration;

--------------- VERIFY ALL THE RECORDS ARE COPIED ------------------

SELECT COUNT(*) FROM DBO.EMP_REMUNERATION;
SELECT COUNT(*) FROM DBO.stg_emp_remuneration;

------------ ASSUME THE NULL VALUES IN EXPENSES ARE ZERO AND REPLACING ---------------

UPDATE DBO.EMP_REMUNERATION SET [EXPENSES] = 0 WHERE [EXPENSES] IS NULL;

----------- CHECK IF ALL UPDATED ------------------------------

SELECT COUNT(*) FROM DBO.EMP_REMUNERATION WHERE [EXPENSES] IS NULL;

----------- CLEAN AND UPDATE COLUMNS BY REMOVING EXTRA SPACES IN LEFT AND RIGHT --------------------------------------

UPDATE DBO.EMP_REMUNERATION 
	SET [NAME]  = UPPER(LTRIM(RTRIM([NAME]))),
		[DEPARTMENT] = UPPER(LTRIM(RTRIM([DEPARTMENT]))),
		[TITLE] = UPPER(LTRIM(RTRIM([TITLE])))
	;

--------- PREVIEW DEPARTMENT VALUES WITH DIFFERENT NAMES- BUT SHOULD BE SAME ---------

SELECT DISTINCT DEPARTMENT FROM DBO.EMP_REMUNERATION WHERE DEPARTMENT LIKE 'FIN%';


---------- REPLACE ALL THE RECORDS IN THAT DEPARTMENT AS 'FINANCE AND RISK MANAGEMENT' -----------------------------------

UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'FINANCE AND RISK MANAGEMENT'
	WHERE DEPARTMENT LIKE 'FIN%';

----------- VERIFY THE UPDATED WORK ---------------------------------------------------------

SELECT DISTINCT DEPARTMENT FROM DBO.EMP_REMUNERATION;

----------- REPLACE THE RECORDS WHERE DEPARTMENT IS HUMAN RESOURCES, HR & DIGITAL STRATEGY AND HUMAN RESOURCE SERVICES INTO ONE ---------

UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'HUMAN RESOURCES'
	WHERE DEPARTMENT LIKE '%DIGITAL STRATEGY%' OR DEPARTMENT LIKE 'HUMAN RESOURCE%';


UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'PLANNING AND DEVELOPMENT'
	WHERE DEPARTMENT LIKE '%PLANNING%';


UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'REAL ESTATE AND FACILITIES MANAGEMENT'
	WHERE DEPARTMENT LIKE 'REAL%';

UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'FIRE AND RESCUE SERVICES'
	WHERE DEPARTMENT LIKE 'VFRS%';

UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'DEVELOPMENT, BUILDING & LICENSING'
	WHERE DEPARTMENT LIKE '%BLDG%';

UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'OFFICE OF THE CHIEF SAFETY OFFICER'
	WHERE DEPARTMENT LIKE '%CHIEF SAFETY OFFICER%';


UPDATE DBO.EMP_REMUNERATION
	SET DEPARTMENT = 'OFFICE OF THE AUDITOR GENERAL'
	WHERE DEPARTMENT LIKE '%OFFICE OF THE AG%';


------------------ VERIFY THE UPDATED RECORDS ---------------------------------------------

SELECT DISTINCT DEPARTMENT FROM DBO.EMP_REMUNERATION;

-------------------- SELECT DISTINCT TITLES -------------------------------------------------

SELECT DISTINCT TITLE FROM DBO.EMP_REMUNERATION;

------------------------ CHECK DISTINCT RECORDS WITH THE TITLE WORKING SITE SUPERVISOR ---------
SELECT DISTINCT TITLE FROM DBO.EMP_REMUNERATION WHERE TITLE LIKE '%WORKING SITE SUPERVISOR%';

------------------------- UPDATE ALL MATCHING TITLES AS 'WORKING SITE SUPERVISOR' -------------

UPDATE DBO.EMP_REMUNERATION 
	SET TITLE = 'WORKING SITE SUPERVISOR'
	WHERE TITLE LIKE 'WORKING SITE SUPERVISOR%';

SELECT DISTINCT TITLE FROM DBO.EMP_REMUNERATION WHERE TITLE LIKE '%WORKING SITE SUPERVISOR%';

------------------------ CHECK DISTINCT RECORDS WITH THE TITLE TEAM LEAD ---------
SELECT DISTINCT TITLE FROM DBO.EMP_REMUNERATION WHERE TITLE LIKE '%TEAM LEAD%';

------------------------- UPDATE ALL MATCHING TITLES -------------------------------------------------
UPDATE DBO.EMP_REMUNERATION
	SET TITLE = REPLACE(TITLE, 'TEAM LEAD LL', 'TEAM LEAD II') WHERE TITLE LIKE 'TEAM LEAD%';
UPDATE DBO.EMP_REMUNERATION
	SET TITLE = REPLACE(TITLE, 'TEAM LEAD IL', 'TEAM LEAD II') WHERE TITLE LIKE 'TEAM LEAD%';
UPDATE DBO.EMP_REMUNERATION
	SET TITLE = REPLACE(TITLE, 'TEAM LEAD IIL', 'TEAM LEAD III') WHERE TITLE LIKE 'TEAM LEAD%';
UPDATE DBO.EMP_REMUNERATION
	SET TITLE = REPLACE(TITLE, 'TEAM LEAD ILL', 'TEAM LEAD III') WHERE TITLE LIKE 'TEAM LEAD%';


------------------------ CHECK DISTINCT RECORDS WITH THE TITLE  ANALYST ---------
SELECT DISTINCT TITLE FROM DBO.EMP_REMUNERATION WHERE TITLE LIKE '%ANALYST%';

UPDATE DBO.EMP_REMUNERATION
	SET TITLE = REPLACE(TITLE, 'BUDGET ANALYST IL', 'BUDGET ANALYST II') WHERE TITLE LIKE 'BUDGET ANALYST%';

UPDATE dbo.EMP_REMUNERATION
SET Title = REPLACE(Title, 'COMPUTER PROGRAMMER/ANALYST', 'COMPUTER PROGRAMMER ANALYST')
WHERE Title LIKE 'COMPUTER PROGRAMMER/ANALYST%';


UPDATE dbo.EMP_REMUNERATION
SET Title = REPLACE(Title, 'COMPUTER PROGRAMMER / ANALYST', 'COMPUTER PROGRAMMER ANALYST')
WHERE Title LIKE 'COMPUTER PROGRAMMER / ANALYST%';


UPDATE dbo.EMP_REMUNERATION
SET Title = REPLACE(Title, 'FINANCIAL ANALYST IL', 'FINANCIAL ANALYST II')
WHERE Title LIKE 'FINANCIAL ANALYST IL';

UPDATE dbo.EMP_REMUNERATION
SET Title = 'MANAGER, WAREHOUSE & BUSINESS ANALYST' WHERE Title LIKE '%WAREHOUSE & BUSINESS ANALYST';

UPDATE dbo.EMP_REMUNERATION
SET Title = 'SYSTEMS ANALYST II' WHERE Title LIKE 'SYSTEM ANALYST IL';

UPDATE dbo.EMP_REMUNERATION
SET Title = 'SYSTEMS ANALYST III' WHERE Title LIKE 'SYSTEM ANALYST ILL';

UPDATE DBO.EMP_REMUNERATION 
	SET TITLE = 'SYSTEMS ANALYST II'
	WHERE TITLE LIKE 'SYSTEM ANALYST II';

UPDATE DBO.EMP_REMUNERATION 
	SET TITLE = 'SYSTEMS ANALYST II'
	WHERE TITLE LIKE 'SYSTEM ANALYST II';

UPDATE DBO.EMP_REMUNERATION 
	SET TITLE = 'SYSTEMS ANALYST III'
	WHERE TITLE LIKE 'SYSTEM ANALYST III';


SELECT * FROM DBO.EMP_REMUNERATION;


