-------------------------------------------------------------------------------------------------------------
                               -- DATA MODELING --
---------------------------------------------------------------------------------------------------------------

-- COPY THE CLEANED DATASET ----------------------------------------
SELECT * INTO DBO.EMP_REMUNERATION_FINAL FROM DBO.EMP_REMUNERATION;

-- VERIFY ALL RECORDS ARE THERE------------------------------------
SELECT * FROM DBO.EMP_REMUNERATION_FINAL;

-- CREATE DIMENSION TABLE FOR DEPARTMENT  ---------------------------------------
DROP TABLE IF EXISTS dbo.DEPARTMENT;
GO
SELECT DISTINCT DEPARTMENT,DENSE_RANK() OVER (ORDER BY DEPARTMENT) AS DEPT_ID INTO DBO.DEPARTMENT FROM DBO.EMP_REMUNERATION_FINAL;
GO

SELECT * FROM DBO.DEPARTMENT ORDER BY DEPT_ID;


-- CREATE DIMENSION TABLE FOR EMPLOYEE  ---------------------------------------
DROP TABLE IF EXISTS DBO.EMPLOYEE;
GO
SELECT DISTINCT NAME, DENSE_RANK() OVER (ORDER BY NAME) AS EMP_ID INTO DBO.EMPLOYEE FROM DBO.EMP_REMUNERATION_FINAL;
GO

SELECT * FROM DBO.EMPLOYEE ORDER BY EMP_ID;

------- CREATE DIMENSION TABLE FOR TITLE ------------------------------------------
DROP TABLE IF EXISTS DBO.TITLE;
GO
SELECT DISTINCT TITLE, DENSE_RANK() OVER (ORDER BY TITLE) AS TITLE_ID INTO DBO.TITLE FROM DBO.EMP_REMUNERATION_FINAL;

SELECT * FROM DBO.TITLE ORDER BY TITLE_ID;

----------- CREATE THE FACT TABLE - PAYROLL -----------------------------------
DROP TABLE IF EXISTS DBO.FACT_COMPENSATION;
GO
SELECT F.[YEAR],
       E.EMP_ID,
       D.DEPT_ID,
       T.TITLE_ID,
       F.REMUNERATION,
       F.EXPENSES,
       (F.REMUNERATION + F.EXPENSES) AS TOTAL_COMPENSATION
 INTO DBO.FACT_COMPENSATION FROM DBO.EMP_REMUNERATION_FINAL F
 JOIN DBO.DEPARTMENT D ON F.DEPARTMENT = D.DEPARTMENT
 JOIN DBO.EMPLOYEE E ON F.NAME = E.NAME
 JOIN DBO.TITLE T ON T.TITLE = F.TITLE;
 GO

 SELECT * FROM DBO.FACT_COMPENSATION;

 ---- VALIDATE THE MODEL -------------
 SELECT COUNT(*) FROM DBO.FACT_COMPENSATION;


 SELECT @@SERVERNAME AS SQL_Instance_Name;
